# -*- coding: utf-8 -*-
"""Customer Churn Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17o2y_NCrLRwY8_nji9dyuItYck42bVLh

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Generate Synthetic Dataset"""

np.random.seed(42)

n = 100000

df = pd.DataFrame({
    "Customer_ID": range(1, n+1),
    "Age": np.random.randint(18, 71, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200001, n),
    "CreditScore": np.random.randint(300, 901, n),
    "EstimatedSalary": np.random.randint(10000, 150001, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice(["Yes", "No"], n),
})

df["Churn"] = (
    (df["Balance"] < 50000) &
    (df["IsActiveMember"] == "No") &
    (df["Tenure"] < 3)
).astype(int)

print(df.head())

"""Data Cleaning & Preprocessing"""

print("\nMissing Values:\n", df.isnull().sum())

print("\nData Types:\n", df.dtypes)

df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df["IsActiveMember"] = df["IsActiveMember"].map({"No": 0, "Yes": 1})

"""Descriptive Statistics"""

print("\nMean:\n", df.mean(numeric_only=True))

print("\nMedian:\n", df.median(numeric_only=True))

print("\nStd Dev:\n", df.std(numeric_only=True))

print("\nMode:\n", df.mode().iloc[0])

"""Churn Behavior Analysis"""

print("\nChurn Count:\n", df["Churn"].value_counts())

print("\nChurn Percentage:\n", df["Churn"].value_counts(normalize=True) * 100)

"""Group-Based Analysis"""

print("\nAge vs Churn:\n", df.groupby("Age")["Churn"].mean())

print("\nGender vs Churn:\n", df.groupby("Gender")["Churn"].mean())

print("\nActive vs Churn:\n", df.groupby("IsActiveMember")["Churn"].mean())

print("\nProducts vs Churn:\n", df.groupby("NumOfProducts")["Churn"].mean())

"""Relationship Analysis"""

print("\nBalance vs Churn:\n", df.groupby("Churn")["Balance"].mean())

print("\nCredit Score vs Churn:\n", df.groupby("Churn")["CreditScore"].mean())

print("\nTenure vs Churn:\n", df.groupby("Churn")["Tenure"].mean())

"""Data Visualization

Bar Chart (Churn Count)
"""

sns.countplot(x="Churn", data=df)
plt.title("Churn Distribution")
plt.show()

"""Pie Chart"""

df["Churn"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Churn Ratio")
plt.ylabel("")
plt.show()

"""Histogram"""

df["Age"].hist()
plt.title("Age Distribution")
plt.show()

"""Scatter Plot"""

plt.scatter(df["Balance"], df["EstimatedSalary"])
plt.title("Balance vs Salary")
plt.xlabel("Balance")
plt.ylabel("Salary")
plt.show()

"""Box Plot"""

sns.boxplot(x="Churn", y="Balance", data=df)
plt.title("Balance vs Churn")
plt.show()

"""Heatmap"""

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()